openapi: 3.1.0
x-stoplight:
  id: 0b810d4c5fc11
info:
  title: Areas API
  summary: The Areas API
  description: Use the Areas API to learn more about Christian.
  version: 0.1.0
  contact:
    name: Christian Areas
    email: me@areas.me
    url: 'https://areas.me'
tags:
  - name: Core
  - name: Life
  - name: Career
servers:
  - url: 'https://{environment}.areas.me/{version}'
    variables:
      environment:
        default: sandbox-api
        enum:
          - api
          - sandbox-api
      version:
        default: beta
        enum:
          - beta
          - v1
paths:
  '/persons':
    post:
      summary: Create a person
      description: 
      operationId: post-persons
      tags:
        - Core
      parameters:
        - in: query
          name: email
          description: The person’s email address.
          schema:
            type: string
          required: true
      responses:
        '200':
          description: You successfully created a person.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          description: You didn’t submit an email address.
        '409':
          description: You submitted an email address for a person that’s already in the system.
components:
  schemas:
    Person:
      $ref: ../data-models/Person.yaml
    Resume:
      $ref: ../data-models/Resume.yaml
    Portfolio:
      $ref: ../data-models/Portfolio.yaml
