openapi: 3.1.0
x-stoplight:
  id: 0b810d4c5fc11
info:
  title: Areas API
  summary: The Areas API
  description: Use the Areas API to learn more about Christian.
  version: 0.1.0
  contact:
    name: Christian Areas
    email: me@areas.me
    url: areas.me
tags:
  - name: Core
  - name: Life
  - name: Career
servers:
  - url: 'https://{environment}.areas.me/{version}'
    variables:
      environment:
        default: api
        enum:
          - api
          - sandbox-api
      version:
        default: beta
        enum:
          - beta
          - v1
paths:
  '/persons/{personId}':
    parameters:
      - schema:
          type: string
        name: personId
        in: path
        required: true
    get:
      summary: Get User Info by User ID
      tags:
        - Core
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '404':
          description: User Not Found
      operationId: get-persons-personId
      description: Retrieve the information of the person with the matching person ID.
    patch:
      summary: Update User Information
      operationId: patch-persons-personId
      tags:
        - Core
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing person.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch person properties to update.
  /persons:
    post:
      summary: Create New User
      operationId: post-persons
      tags:
        - Core
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
        description: Post the necessary fields for the API to create a new person.
      description: Create a new person.
    parameters: []
components:
  schemas:
    Person:
      $ref: '../data-models/Person.yaml'
    Resume:
      $ref: '../data-models/Resume.yaml'
    Portfolio:
      $ref: '../data-models/Portfolio.yaml'
